### PR TITLE
Docker/setup

### PR DESCRIPTION
**Pull request by vyzaldysanchez**
This is the docker configuration for this project.

### CODE REVIEW

**Comment by LeonelSantiago** [comment]
@vyzaldysanchez check this conflicts

**Comment by vyzaldysanchez** [comment]
@LeonelSantiago fixed conflicts.

**Comment by vyzaldysanchez** [comment]
I removed those hardcoded values and added new instructions in the readme.

**Comment by LeonelSantiago** [comment]
Nice!

**Pull request merged**
